#!/bin/bash
# Creates the MongoDB auth Secret from passwords generated by Terraform.
# The Bitnami chart reads this Secret (auth.existingSecret) and does not create it.
set -euo pipefail

KUBECONFIG_PATH=$1
ROOT_PASSWORD=$2
APP_PASSWORD=$3
REPLICA_SET_KEY=$4

export KUBECONFIG="$KUBECONFIG_PATH"

kubectl apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: default
type: Opaque
stringData:
  mongodb-root-password: ${ROOT_PASSWORD}
  mongodb-passwords: ${APP_PASSWORD}
  mongodb-replica-set-key: ${REPLICA_SET_KEY}
EOF
